### ISSUE TITLE
Sendy implementation

### ISSUE THREAD

**Issue by glotato** [politicalrev/wp.thepoliticalrev.org#11]
Sorry if this is finished or listed elsewhere

**Comment by Smona** [comment]
@innovativedmm this was fixed, right?

**Comment by Smona** [comment]
@glotato this is not an issue with the website code. And fortunately Amanda has already implemented it.

I'm glad you submitted this anyway, because it highlights that we didn't talk about a process for reporting and tracking technical issues outside of a specific topic. Might be something to discuss in the dev-pro channel!
